### ISSUE TITLE
Annotations in data dir

### ISSUE THREAD

**Issue by faroit** [marl/medleydb#18]
Recently the annotations have been added to the data dir of this repo

* Could you elaborate (in the readme) why this has been done?
* What about the annotations in the original medleydb folder? I guess the ones within the data folder are more up to date. So they will be discarded, correct?
* If there are different version of the dataset around it would make sense to version (and add MD5 hashes) the tar.gz files as well and provide more information on the medleydb website.

**Comment by rabitt** [comment]
* Could you elaborate (in the readme) why this has been done?

I made the structure update (admittedly) in a bit of a hurry. I think the way the data is now is not the right solution and I'm going to restructure the repository again so that the audio can live completely separately from the annotations. I'll also update the readme :)

* What about the annotations in the original medleydb folder? I guess the ones within the data folder are more up to date. So they will be discarded, correct?

In short, the original annotations from the download will become obsolete. In the future I'm going to have the most up to date annotations live in the github repository (versioned of course) and will distribute the audio via the website. I'm working on this now and will update everything asap.

*If there are different version of the dataset around it would make sense to version (and add MD5 hashes) the tar.gz files as well and provide more information on the medleydb website.

Yes absolutely. We haven't finished/released the second version yet but it should be out in the next couple of months.

**Comment by faroit** [comment]
sounds good ;-)
